/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksRouteImport } from './routes/books'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as TvRouteImport } from './routes/tv'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminIdRouteImport } from './routes/admin/$id'
import { Route as AdminImportRouteImport } from './routes/admin/import'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as ApiItemsRouteImport } from './routes/api/items'
import { Route as GenreSlugRouteImport } from './routes/genre.$slug'
import { Route as ItemSlugRouteImport } from './routes/item.$slug'
import { Route as KeywordSlugRouteImport } from './routes/keyword.$slug'
import { Route as ApiItemsIdRouteImport } from './routes/api/items.$id'
import { Route as ApiItemsSyncRouteImport } from './routes/api/items/sync'
import { Route as BooksListSlugRouteImport } from './routes/books_.list.$slug'
import { Route as MoviesListSlugRouteImport } from './routes/movies_.list.$slug'
import { Route as TvListSlugRouteImport } from './routes/tv_.list.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItemsRoute = ApiItemsRouteImport.update({
  id: '/api/items',
  path: '/api/items',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreSlugRoute = GenreSlugRouteImport.update({
  id: '/genre/$slug',
  path: '/genre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemSlugRoute = ItemSlugRouteImport.update({
  id: '/item/$slug',
  path: '/item/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordSlugRoute = KeywordSlugRouteImport.update({
  id: '/keyword/$slug',
  path: '/keyword/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItemsIdRoute = ApiItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiItemsRoute,
} as any)
const ApiItemsSyncRoute = ApiItemsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => ApiItemsRoute,
} as any)
const BooksListSlugRoute = BooksListSlugRouteImport.update({
  id: '/books_/list/$slug',
  path: '/books/list/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesListSlugRoute = MoviesListSlugRouteImport.update({
  id: '/movies_/list/$slug',
  path: '/movies/list/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TvListSlugRoute = TvListSlugRouteImport.update({
  id: '/tv_/list/$slug',
  path: '/tv/list/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/movies': typeof MoviesRoute
  '/tv': typeof TvRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/api/items': typeof ApiItemsRouteWithChildren
  '/genre/$slug': typeof GenreSlugRoute
  '/item/$slug': typeof ItemSlugRoute
  '/keyword/$slug': typeof KeywordSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/items/$id': typeof ApiItemsIdRoute
  '/api/items/sync': typeof ApiItemsSyncRoute
  '/books/list/$slug': typeof BooksListSlugRoute
  '/movies/list/$slug': typeof MoviesListSlugRoute
  '/tv/list/$slug': typeof TvListSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/movies': typeof MoviesRoute
  '/tv': typeof TvRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/api/items': typeof ApiItemsRouteWithChildren
  '/genre/$slug': typeof GenreSlugRoute
  '/item/$slug': typeof ItemSlugRoute
  '/keyword/$slug': typeof KeywordSlugRoute
  '/admin': typeof AdminIndexRoute
  '/api/items/$id': typeof ApiItemsIdRoute
  '/api/items/sync': typeof ApiItemsSyncRoute
  '/books/list/$slug': typeof BooksListSlugRoute
  '/movies/list/$slug': typeof MoviesListSlugRoute
  '/tv/list/$slug': typeof TvListSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/movies': typeof MoviesRoute
  '/tv': typeof TvRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/api/items': typeof ApiItemsRouteWithChildren
  '/genre/$slug': typeof GenreSlugRoute
  '/item/$slug': typeof ItemSlugRoute
  '/keyword/$slug': typeof KeywordSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/items/$id': typeof ApiItemsIdRoute
  '/api/items/sync': typeof ApiItemsSyncRoute
  '/books_/list/$slug': typeof BooksListSlugRoute
  '/movies_/list/$slug': typeof MoviesListSlugRoute
  '/tv_/list/$slug': typeof TvListSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/movies'
    | '/tv'
    | '/admin/$id'
    | '/admin/import'
    | '/admin/login'
    | '/admin/new'
    | '/api/items'
    | '/genre/$slug'
    | '/item/$slug'
    | '/keyword/$slug'
    | '/admin/'
    | '/api/items/$id'
    | '/api/items/sync'
    | '/books/list/$slug'
    | '/movies/list/$slug'
    | '/tv/list/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/movies'
    | '/tv'
    | '/admin/$id'
    | '/admin/import'
    | '/admin/login'
    | '/admin/new'
    | '/api/items'
    | '/genre/$slug'
    | '/item/$slug'
    | '/keyword/$slug'
    | '/admin'
    | '/api/items/$id'
    | '/api/items/sync'
    | '/books/list/$slug'
    | '/movies/list/$slug'
    | '/tv/list/$slug'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/movies'
    | '/tv'
    | '/admin/$id'
    | '/admin/import'
    | '/admin/login'
    | '/admin/new'
    | '/api/items'
    | '/genre/$slug'
    | '/item/$slug'
    | '/keyword/$slug'
    | '/admin/'
    | '/api/items/$id'
    | '/api/items/sync'
    | '/books_/list/$slug'
    | '/movies_/list/$slug'
    | '/tv_/list/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRoute
  MoviesRoute: typeof MoviesRoute
  TvRoute: typeof TvRoute
  AdminIdRoute: typeof AdminIdRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewRoute: typeof AdminNewRoute
  ApiItemsRoute: typeof ApiItemsRouteWithChildren
  GenreSlugRoute: typeof GenreSlugRoute
  ItemSlugRoute: typeof ItemSlugRoute
  KeywordSlugRoute: typeof KeywordSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BooksListSlugRoute: typeof BooksListSlugRoute
  MoviesListSlugRoute: typeof MoviesListSlugRoute
  TvListSlugRoute: typeof TvListSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$id': {
      id: '/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items': {
      id: '/api/items'
      path: '/api/items'
      fullPath: '/api/items'
      preLoaderRoute: typeof ApiItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$slug': {
      id: '/genre/$slug'
      path: '/genre/$slug'
      fullPath: '/genre/$slug'
      preLoaderRoute: typeof GenreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$slug': {
      id: '/item/$slug'
      path: '/item/$slug'
      fullPath: '/item/$slug'
      preLoaderRoute: typeof ItemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keyword/$slug': {
      id: '/keyword/$slug'
      path: '/keyword/$slug'
      fullPath: '/keyword/$slug'
      preLoaderRoute: typeof KeywordSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items/$id': {
      id: '/api/items/$id'
      path: '/$id'
      fullPath: '/api/items/$id'
      preLoaderRoute: typeof ApiItemsIdRouteImport
      parentRoute: typeof ApiItemsRoute
    }
    '/api/items/sync': {
      id: '/api/items/sync'
      path: '/sync'
      fullPath: '/api/items/sync'
      preLoaderRoute: typeof ApiItemsSyncRouteImport
      parentRoute: typeof ApiItemsRoute
    }
    '/books_/list/$slug': {
      id: '/books_/list/$slug'
      path: '/books/list/$slug'
      fullPath: '/books/list/$slug'
      preLoaderRoute: typeof BooksListSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies_/list/$slug': {
      id: '/movies_/list/$slug'
      path: '/movies/list/$slug'
      fullPath: '/movies/list/$slug'
      preLoaderRoute: typeof MoviesListSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv_/list/$slug': {
      id: '/tv_/list/$slug'
      path: '/tv/list/$slug'
      fullPath: '/tv/list/$slug'
      preLoaderRoute: typeof TvListSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiItemsRouteChildren {
  ApiItemsIdRoute: typeof ApiItemsIdRoute
  ApiItemsSyncRoute: typeof ApiItemsSyncRoute
}

const ApiItemsRouteChildren: ApiItemsRouteChildren = {
  ApiItemsIdRoute: ApiItemsIdRoute,
  ApiItemsSyncRoute: ApiItemsSyncRoute,
}

const ApiItemsRouteWithChildren = ApiItemsRoute._addFileChildren(
  ApiItemsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRoute,
  MoviesRoute: MoviesRoute,
  TvRoute: TvRoute,
  AdminIdRoute: AdminIdRoute,
  AdminImportRoute: AdminImportRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewRoute: AdminNewRoute,
  ApiItemsRoute: ApiItemsRouteWithChildren,
  GenreSlugRoute: GenreSlugRoute,
  ItemSlugRoute: ItemSlugRoute,
  KeywordSlugRoute: KeywordSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BooksListSlugRoute: BooksListSlugRoute,
  MoviesListSlugRoute: MoviesListSlugRoute,
  TvListSlugRoute: TvListSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
